name: 'DAppNode package build action'
description: 'Builds and uploads a release to IPFS and comments its hash in the PR'
author: 'DAppNode Association'

inputs:
  GITHUB_TOKEN:
    description: 'Set a generated GITHUB_TOKEN for pushing to the remote branch.'
    required: true
  PINATA_API_KEY:
    description: 'API_KEY key to push to pinata.'
    required: true
  PINATA_SECRET_API_KEY:
    description: 'SECRET_API_KEY to push to pinata.'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
